### ISSUE TITLE
[TYPO] in [SvcQC.MAM01.3] 

### ISSUE THREAD

**Issue by micafer** [EOSC-synergy/service-qa-baseline#1]
## Describe and locate the typo
It seems that the that somthing is missing in this sentence:

```
[SvcQC.MAM01.3] The Service SHOULD for security related criteria (DAST).
```

**Comment by mariojmdavid** [comment]
solved in commit 713690f11c74c7bec226a463fb5520082d8ebd5a
also improved section on Monitoring
