### ISSUE TITLE
[ENHANCEMENT] Add specific section for API testing 

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/service-qa-baseline#10]
## Please elaborate here on the enhancement request.
Since APIs are common to services, it makes sense to highlight the role of APIs

## Describe the solution you'd like
An individual `API Testing` section that can be then referred by the integration and functional testing sections

## Additional context
See PR https://github.com/EOSC-synergy/service-qa-baseline/pull/9

**Comment by mariojmdavid** [comment]
section added in PR https://github.com/EOSC-synergy/service-qa-baseline/pull/9
