### ISSUE TITLE
[ENHANCEMENT] Consider DevSecOps practices

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/service-qa-baseline#11]
## Please elaborate here on the enhancement request.
The `Security` section must consider DevSecOps

## Describe the solution you'd like
Security section aligned with DevSecOps

## Additional context
NA

**Comment by orviz** [comment]
addressed in https://github.com/EOSC-synergy/service-qa-baseline/pull/18

**Comment by mariojmdavid** [comment]
merged
