### ISSUE TITLE
[ENHANCEMENT] Add introductory text to all sections

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/service-qa-baseline#14]
## Please elaborate here on the enhancement request.
Some sections do not have introductory text.

## Describe the solution you'd like
It is good to have 1/2 sentences to introduce the 'what' (the 'how' is then tackled by the criteria)

## Additional context
NA

**Comment by mariojmdavid** [comment]
introductory text added to all sections, fixed by commit 557d47864ad5335787de876647effce15651b03e
