### ISSUE TITLE
[ENHANCEMENT] Reorganize criteria categories

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/service-qa-baseline#16]
## Please elaborate here on the enhancement request.
Put related categories together

## Describe the solution you'd like
* `Monitoring` followed by `Automated deployment` followed by `Metrics`
* `Security` followed by `Policies` followed by `Support`

## Additional context
NA

**Comment by mariojmdavid** [comment]
done in commit 557d47864ad5335787de876647effce15651b03e
