### ISSUE TITLE
[TYPO]  Scattered Typos

### ISSUE THREAD

**Issue by gmolto** [EOSC-synergy/service-qa-baseline#19]
## Describe and locate the typo
Brief description of the typo that has been spotted.

[SvcQC.Fun]
 - This type of Service testing focus --> focuses

[SvcQC.Per]
 - Scalability testing is test --> is *a* test

[SvcQC.Per03]  
  - when its load reach the limits --> when its load reaches the limits
  - hability --> ability

[SvcQC.Per04] 
  - hability --> ability

[SvcQC.Met01.1]
  - comulative --> cumulative

## Expected content
Add the expected or fixed content.

## Additional context
If needed, add here the sources/references that support the change.

**Comment by mariojmdavid** [comment]
solved in commit e9d886a84169bde988edb5af3d24df958609250d
