### ISSUE TITLE
[ENHANCEMENT] in [SvcQC.Fun01.2]. Public APIs MUST be included

### ISSUE THREAD

**Issue by micafer** [EOSC-synergy/service-qa-baseline#2]
## Please elaborate here on the enhancement request.
I think that in case of functional tests the public APIs must be included (not only should).
Public APIs is the entrance point for any service so it MUST be included in the functional tests. 

## Describe the solution you'd like
I propose to change the SHOULD to a MUST:

```
[SvcQC.Fun01.2] Functional tests MUST include the public APIs of the Service.
```

**Comment by mariojmdavid** [comment]
agree, solved in commit aac2241fcf57f09c212769f4a915b492d99706c2
in the devel/V1.0 branch
