### ISSUE TITLE
[HELP] Docker image licensing

### ISSUE THREAD

**Issue by samuelbernardolip** [EOSC-synergy/service-qa-baseline#21]
When looking into docker image licensing, question arises about what should be expected from SQA.

Can you use the image? Typically yes.
Strictly speaking, only if you comply with the license of the image and the licenses of all included software. In absence of a license, all rights are reserved. It is your responsibility to check the license status.[1]
Can you modify the image (use as base image)? Typically yes.
Strictly speaking, only if this is allowed by the license of the base image and the licenses of all affected software.[1]
Can you distribute the (modified) image (outside docker hub)? Typically yes but there may be additional requirements.
Strictly speaking, only if this is allowed by the license of the base image and the licenses of all included software.[1]
Can you build the docker image (from the Dockerfile)? Typically yes.
Strictly speaking, only if this is allowed by the license of the build scripts, the licenses of the base image, and the licenses of all included software.[1]

[1] https://opensource.stackexchange.com/questions/7013/license-for-docker-images

**Comment by mariojmdavid** [comment]
not applicable, close after discussion
