### ISSUE TITLE
[TYPO] Some Errata Across the Document

### ISSUE THREAD

**Issue by gmolto** [EOSC-synergy/service-qa-baseline#3]
## Describe and locate the typo
Brief description of the typo that has been spotted.

[Abstract]
 -  Elated --> Related 

[Copyright Notice]
  - collaborations --> collaboration
  - there is a more pragmatic vision [that] the customer ...

[Contextualization of a Service]
  - represent the following --> represents the following

[Quality Criteria]
  - [1], for such cases --> [1]. For such cases, 

[Integration Testing]
  - among coupled Service --> among coupled Services

[SvcQC.Pol01.1]
  - Acceptable Usage Policy vs acceptable use policy (it is repeated three times in that sentence with different nomenclature)

[SvcQC.Pol01.2] The Access Policy, mandate --> The Access Policy mandates

[SvcQC.Pol01.3] Stated --> It states 

## Expected content
Reported above

## Additional context
If needed, add here the sources/references that support the change.

Not needed.

**Comment by mariojmdavid** [comment]
typos fixed in commit 612470450cbfafb9dad9bacb020a6bf320f5be82
of devel/V1.0 branch
