### ISSUE TITLE
[TYPO] Missing Link to Section [SQA-QC.Sec] in SvcQC.Sec

### ISSUE THREAD

**Issue by gmolto** [EOSC-synergy/service-qa-baseline#34]
## Describe and locate the typo
In section 6.6 there is a mention to section [SQA-QC.Sec] that is not in the present document. A link or a reference should be provided.

## Expected content
A link or a reference to section [SQA-QC.Sec] in the corresponding document should be provided.

## Additional context
N.A.

**Comment by mariojmdavid** [comment]
a reference to SQA baseline is already in the doc and reference to that specific section
nonetheless I have put the full section title as reference.
will be in the next commit of the doc
