### ISSUE TITLE
[ENHANCEMENT] Broadening the definition of Web App

### ISSUE THREAD

**Issue by gmolto** [EOSC-synergy/service-qa-baseline#4]
## Please elaborate here on the enhancement request.
A clear and concise description of what the proposed enhancement is all about.

In section [Contextualization of a Service] it is said that a web application is a software program that runs on a web server. This is not always the case, as there are web apps based on the JAMStack, i.e., using static web sites (with only HTML, CSS, JavaScript) which are considered web apps but run exclusively in the web browser (not on the web server).

## Describe the solution you'd like
A clear and concise description of what you want to happen. Please indicate whether a new section is required.

I propose rephrasing as follows: A Web application (Web app) is a software program that is delivered over the Internet and is accessed through a web browser.

## Additional context
Add any other context or references to support your enhancement request.

This is inline with the definition given in https://searchsoftwarequality.techtarget.com/definition/Web-application-Web-app
but removing the term "remote server" since a static web app may be served out of an object storage system (such as Amazon S3) or an external service such as GitHub (e.g. GitHub Pages).

**Comment by mariojmdavid** [comment]
agree

**Comment by mariojmdavid** [comment]
solved in commit 364a4ee924bfc164d7a24794af468da9a94d40e6
in devel/V1.0 branch
