### ISSUE TITLE
[ENHANCEMENT] Broadening the reference to Cloud layer

### ISSUE THREAD

**Issue by gmolto** [EOSC-synergy/service-qa-baseline#5]
## Please elaborate here on the enhancement request.
A clear and concise description of what the proposed enhancement is all about.

In section [Elasticity tests] it is mentioned "cloud layer" but this could be broadened, in order to include services that may be offered by an organization which are not based on Cloud technologies (for example a set of web-based services running on an HPC facility)

## Describe the solution you'd like
A clear and concise description of what you want to happen. Please indicate whether a new section is required.

I propose substituting the term "cloud layer" by "underlying computing infrastructure".

## Additional context
Add any other context or references to support your enhancement request.

**Comment by mariojmdavid** [comment]
I agree
the definition I found was to tied to cloud, will let Pablo comment as well

**Comment by mariojmdavid** [comment]
solved in commit a2b9f462c94aedffc703caf6413a3ed13e3300b6
