### ISSUE TITLE
[ENHANCEMENT] Relaxing the Requirement for License Documentation

### ISSUE THREAD

**Issue by gmolto** [EOSC-synergy/service-qa-baseline#6]
## Please elaborate here on the enhancement request.
A clear and concise description of what the proposed enhancement is all about.

[SvcQC.Doc06] is currently set to MUST but I suggest lowering it to SHOULD, since many open-source projects already include a software license that applies not only to the software itself but also to the documentation. For example, Kubernetes is based on the Apache 2.0 LICENSE, where it is stated the following sentence: 
```
Source" form shall mean the preferred form for making modifications, including but not limited to software source code, documentation source, and configuration files.
```
Therefore, the documentation inherits the license of the software and there should not be mandatory to include another license for it.

## Describe the solution you'd like
A clear and concise description of what you want to happen. Please indicate whether a new section is required.

I suggest switching [SvcQC.Doc06] from MUST to SHOULD.

## Additional context
Add any other context or references to support your enhancement request.

**Comment by mariojmdavid** [comment]
Currently we have
**[SvcQC.Doc06]** Documentation MUST have a non-software license.
note the "non-software" license
for open source SW, (as you said) the License maybe inherited by the documentation, but there is also cases, (openstack for example), that have CREATIVE COMMONS, open access documentation
and finally the issue with closed/property SW, that eosc can have services from it, so the documentation has to be somehow open

**Comment by mariojmdavid** [comment]
doc MUST have a license, but SW license may already include the documentation

**Comment by mariojmdavid** [comment]
nonetheless, we will change to SHOULD

**Comment by mariojmdavid** [comment]
solved in branch dev
