### ISSUE TITLE
[INCONSISTENCY] Merging [SvcQC.Sec05] with [SvcQC.Sec01]

### ISSUE THREAD

**Issue by gmolto** [EOSC-synergy/service-qa-baseline#7]
## Describe and locate the inconsistency
Brief description of the typo that has been spotted.

[SvcQC.Sec05] could be merged with [SvcQC.Sec01] to read as follows: The Service public endpoints and APIs MUST be secured with strong ciphers for encryption.

## Expected content
Add the expected or fixed content.

## Additional context
Add here the sources/references that support the change.

**Comment by mariojmdavid** [comment]
the pragmatic approach is that each criteria will translate into "1" test, so merging would mean 1 criteria for 2 tests, but will let Pablo into the discussion

**Comment by mariojmdavid** [comment]
solved in version v1.0
