### ISSUE TITLE
[INCONSISTENCY] Merging [SvcQC.MAM01.1] and [SvcQC.MAM01.2]

### ISSUE THREAD

**Issue by gmolto** [EOSC-synergy/service-qa-baseline#8]
## Describe and locate the inconsistency
Brief description of the typo that has been spotted.

[SvcQC.MAM01.1] and [SvcQC.MAM01.2] could be merged to read: "The Service public endpoints and APIs SHOULD be monitored" (following the same style of redaction as in [SvcQC.Sec01])

## Expected content
Add the expected or fixed content.

## Additional context
Add here the sources/references that support the change.

**Comment by mariojmdavid** [comment]
there where quite some changes to the monitoring section, but at the moment we have indeed
**[SvcQC.Mon02.1]** The **Service** MUST be monitored for public endpoints
  and APIs secured and strong ciphers for encryption. Use Security tests of
  criteria [SvcQC.Sec02] and [SvcQC.Sec05].
I will close this issue, but it will depend on the discussion in issue #7
